### PR TITLE
Fix payment method/status filtering, values in order list

### PR DESCRIPTION
**Pull request by tobiaseichert**
Here's a patch which should take care of

https://bugs.oxid-esales.com/view.php?id=6774

Please review.

### CODE REVIEW

**Comment by tobiaseichert** [comment]
Using "OrderList_parent" instead of "\OxidEsales\Eshop\Application\Controller\Admin\OrderList" should also work in this case. Problem is that PHPStorm doesn't know about about those "_parent" classes which breaks my xdebug workflow completely. Do you know a way around this? See also https://forum.oxid-esales.com/t/phpstorm-oxid6-parent-klassen-werden-nicht-erkannt/93962 (in German).

**Comment by Sieg** [comment]
@tobiaseichert, are you referring to OXID-eSales ide helper module? or some other one?

**Comment by Sieg** [comment]
Thank you for your knowledge share @tobiaseichert, we will check what can be done.

**Comment by tobiaseichert** [comment]
Thanks, that would be really helpful. In the meantime, I updated the patch as requested, s. my second pull request.

**Comment by Sieg** [comment]
Thanks for the fix, @tobiaseichert!

**Pull request merged**
